# Port to use for the server if no environment variable present
# Ideally an env_var PORT will be there since we're cloud hosting
default_port: 9081

# Regex to validate usernames against
username_regex: "^[\\w ,\\-']{1,20}$"